# This file was generated by GoReleaser. DO NOT EDIT.
cask "octl" do
  version "1.2.1"

  on_macos do
    on_arm do
      sha256 "643116c2bc62f7d6246dea0325dd07bf803692ce54b314771021d74675a79da6"
      url "https://github.com/stellwerk-labs/platform-orchestrator-cli/releases/download/v#{version}/platform-orchestrator-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7435e0acaa8245745eed9e212af507fa4ffc0967776e0cfad63f3bf60b46f79a"
      url "https://github.com/stellwerk-labs/platform-orchestrator-cli/releases/download/v#{version}/platform-orchestrator-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "907309c9c3fbe352466b180ed8e7eae67f438402577d35077263fe115420e415"
      url "https://github.com/stellwerk-labs/platform-orchestrator-cli/releases/download/v#{version}/platform-orchestrator-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7a7d77b0bbf00aa22a7918071949535663e8f95bec84c5f29daa59a6932b3564"
      url "https://github.com/stellwerk-labs/platform-orchestrator-cli/releases/download/v#{version}/platform-orchestrator-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "octl"
  desc "The CLI for Stellwerk, octl."
  homepage "https://docs.stellwerk.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "octl"

  # No zap stanza required
end
