# This file was generated by GoReleaser. DO NOT EDIT.
cask "octl" do
  version "2.0.0"

  on_macos do
    on_arm do
      sha256 "7644b0256e278898081eeb7dd825754455979b5455e8eee4e0e3c2cb84a3f657"
      url "https://github.com/stellwerk-labs/platform-orchestrator-cli/releases/download/v#{version}/platform-orchestrator-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f8e6ba413823b767948a8e60aeed2b9400c1772b2d8790adf22856b7c6f5e59c"
      url "https://github.com/stellwerk-labs/platform-orchestrator-cli/releases/download/v#{version}/platform-orchestrator-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fc2b55c83127f7741a4b6d2d5482f58f0f42bf138965d314c451e0e0f17ec0fc"
      url "https://github.com/stellwerk-labs/platform-orchestrator-cli/releases/download/v#{version}/platform-orchestrator-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9a97a2f3df9e7b882cac42a7f07f788f0b7aead39be74e3eec526ea33df3b7b6"
      url "https://github.com/stellwerk-labs/platform-orchestrator-cli/releases/download/v#{version}/platform-orchestrator-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "octl"
  desc "The CLI for Stellwerk, octl."
  homepage "https://docs.stellwerk.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "octl"

  # No zap stanza required
end
