# This file was generated by GoReleaser. DO NOT EDIT.
cask "octl" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "73819a6332824b02ea1363eff1f1a9993e983c1741f96e6f95cfa675fda6db80"
      url "https://github.com/stellwerk-labs/platform-orchestrator-cli/releases/download/v#{version}/platform-orchestrator-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d65ef7380fa6d53ee24748a2457db5a140b528f22828dcb3f483d1afd80d5a4b"
      url "https://github.com/stellwerk-labs/platform-orchestrator-cli/releases/download/v#{version}/platform-orchestrator-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b1874a840a2de4f06a2063b1fb9ed020a16b77eaf44b5ed45bc8ab398ee575a8"
      url "https://github.com/stellwerk-labs/platform-orchestrator-cli/releases/download/v#{version}/platform-orchestrator-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d4e44a65f0fa4b1b1cb9ffa436d695f704f46547146f59a48d22a4b898993d45"
      url "https://github.com/stellwerk-labs/platform-orchestrator-cli/releases/download/v#{version}/platform-orchestrator-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "octl"
  desc "The CLI for Stellwerk, octl."
  homepage "https://docs.stellwerk.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "octl"

  # No zap stanza required

end
